### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by jipr311** [jmptbl/python-zint#6]
am doing under Ubuntu:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
##
import zint
import sys
##

def on_message():
    print("Hello World!")

if __name__ == '__main__':
    on_message() 
```

but i get the error:

> Traceback (most recent call last):
> File "ApiZint.py", line 8, in <module>
>    import zint
> ...
> OSError: libzint.dll: cannot open shared object file: No such file or directory

**Comment by outdooracorn** [comment]
I just came across this error too. For @jipr311 or anyone else reading this, here is what I found:

Looking at the source code it appears that python-zint doesn't ship with the zint library (libzint). Instead [zint.py](https://github.com/jmptbl/python-zint/blob/master/zint/zint.py) tries to load one of `libzint.so`, `libzint.dylib` or `libzint.dll`. If it can't load any of them (probably because it's not installed) you get the error you're receiving.

To fix this you need to install the libzint. For me on Manjaro that was as simple as installing zint from the [official repositories](https://discover.manjaro.org/packages/zint). It doesn't seem to be [packaged on Ubuntu](https://packages.ubuntu.com/search?suite=eoan&section=all&arch=any&keywords=zint&searchon=names) so it looks like you will have to [compile it from source](http://www.zint.org.uk/Manual.aspx?type=p&page=2) yourself.

**Comment by frkn3206** [comment]
Download and install the file from the official site, then install the python library. then run this code:
    - sudo ldconfig
    - 
and try again
